# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('crawler_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('thumbnail_url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('title', 'created', 'crawler_id'),
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('push_token', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('crawler_id', models.CharField(max_length=100)),
                ('latest_pushtime', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('user_id', 'crawler_id'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_auth', models.CharField(default=b'False', max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_login', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('user_id', 'crawler_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='pushtoken',
            unique_together=set([('user_id', 'push_token')]),
        ),
    ]
