# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoriCrawlerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='link_url',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crawler',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
