# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osoriCrawlerAPI', '0003_auto_20160824_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('user_id', 'crawler_name')},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='crawlerName',
            new_name='crawler_name',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='uid',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='crawler_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='latest_pushtime',
            field=models.DateField(default=datetime.datetime(2016, 8, 25, 7, 8, 27, 777681, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
